version: "3"
services:
  dividisaggiamente:
    container_name: dividisaggiamente
    build: .
    command: nodemon -L --watch . -e js app.js
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www
    links:
      - "mongo:mongohost"
  mongo-project:
    container_name: mongo-project
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"